app = "video-downloader"
primary_region = "arn"

# Build configuration (uses your Dockerfile)
[build]
  dockerfile = "Dockerfile"

# Define the process (your bot runs as a single process)
[processes]
  app = ""  # Empty command; uses Dockerfile's CMD ["./bot"]

# Machine configuration (VM settings)
[[vm]]
  cpu_kind = "shared"  # Shared CPU for cost efficiency
  cpus = 1            # 1 vCPU
  memory = "256mb"    # 256 MB RAM (lightweight bot)